### PR TITLE
Add support for syntax highlighting

### PR DESCRIPTION
**Pull request by jihchi**
It would be useful for people to interact with the CLI.

For example:

```sh
curl -sL google.com | htmlq -h -p html body \#gbar
```

### CODE REVIEW

**Comment by Alhadis** [comment]
This is arguably the domain of a dedicated syntax highlighter (e.g., `bat`):

~~~console
$ curl -sL google.com | htmlq -p html body div | bat -lhtml
~~~

I mean, it looks nice out-of-the-box, but what if users want to post-process the output *and* highlight it?

Just some food for thought.

**Comment by jihchi** [comment]
@Alhadis I wasn’t aware of that we can utilize `bat` to do the syntax highlighting!

I am adding a new argument (e.g. `-h/—syntax-highlighting`) to enable the feature and disable it by default.

Thanks for the comments/thoughts! This is why I created this draft PR!

**Comment by Alhadis** [comment]
No problem. IMHO, it might be better to recommend tools like `bat` (or any others you know of) in the readme, which would spare you the burden of keeping `htmlq`'s highlighting up-to-date with other tools for highlighting source code.

**Comment by jihchi** [comment]
Closing this PR in favor of #18 .

**Pull request closed without merging**
